exclude: [README.md, resources/src]
title: Computational Linguistics at ILLC
email: w.aziz@uva.nl
description: > 
    This is where you will find all about computational linguistics at the ILLC.
url: "//cl-illc.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: cl-illc
paginate: 3

# useful links
illc_url: http://www.illc.uva.nl
uva_url: http://www.uva.nl/en/home

# Build settings
markdown: kramdown

